"""initial_schema

Revision ID: 36c9c84feae3
Revises: 
Create Date: 2026-09-22 10:08:54.209376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c9c84feae3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('opening_hours', sa.String(length=100), nullable=False),
    sa.Column('estimated_cost', sa.Integer(), nullable=False),
    sa.Column('price_level', sa.String(length=10), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('best_time', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('why_recommended', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_category'), 'places', ['category'], unique=False)
    op.create_index(op.f('ix_places_city'), 'places', ['city'], unique=False)
    op.create_index(op.f('ix_places_name'), 'places', ['name'], unique=False)
    op.create_index(op.f('ix_places_verification_status'), 'places', ['verification_status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('locals',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('why_choose_me', sa.Text(), nullable=True),
    sa.Column('expertise', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('consultation_fee', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('years_local', sa.Integer(), nullable=False),
    sa.Column('travelers_helped', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('availability', sa.String(length=200), nullable=False),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('local_picks', sa.JSON(), nullable=False),
    sa.Column('reels', sa.JSON(), nullable=False),
    sa.Column('places_i_love_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locals_city'), 'locals', ['city'], unique=False)
    op.create_index(op.f('ix_locals_verification_status'), 'locals', ['verification_status'], unique=False)
    op.create_table('saved_places',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'place_id', name='uq_user_saved_place')
    )
    op.create_index(op.f('ix_saved_places_place_id'), 'saved_places', ['place_id'], unique=False)
    op.create_index(op.f('ix_saved_places_user_id'), 'saved_places', ['user_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.String(length=20), nullable=False),
    sa.Column('arrival_time', sa.String(length=20), nullable=False),
    sa.Column('departure_time', sa.String(length=20), nullable=False),
    sa.Column('travelers', sa.String(length=20), nullable=False),
    sa.Column('budget', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('travel_style', sa.String(length=50), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_destination'), 'trips', ['destination'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('traveler_id', sa.String(length=36), nullable=True),
    sa.Column('local_id', sa.String(length=60), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=False),
    sa.Column('start_time', sa.String(length=30), nullable=False),
    sa.Column('end_time', sa.String(length=30), nullable=True),
    sa.Column('travelers', sa.String(length=20), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('booking_status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_status'), 'bookings', ['booking_status'], unique=False)
    op.create_index(op.f('ix_bookings_local_id'), 'bookings', ['local_id'], unique=False)
    op.create_index(op.f('ix_bookings_traveler_id'), 'bookings', ['traveler_id'], unique=False)
    op.create_table('concierge_requests',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('timing', sa.String(length=100), nullable=False),
    sa.Column('preferred_date', sa.String(length=30), nullable=True),
    sa.Column('budget', sa.String(length=50), nullable=True),
    sa.Column('travelers', sa.String(length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_local_id', sa.String(length=60), nullable=True),
    sa.Column('updates', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_local_id'], ['locals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concierge_requests_destination'), 'concierge_requests', ['destination'], unique=False)
    op.create_index(op.f('ix_concierge_requests_status'), 'concierge_requests', ['status'], unique=False)
    op.create_index(op.f('ix_concierge_requests_user_id'), 'concierge_requests', ['user_id'], unique=False)
    op.create_table('itinerary_days',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('trip_id', sa.String(length=60), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_days_trip_id'), 'itinerary_days', ['trip_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('place_id', sa.String(length=60), nullable=True),
    sa.Column('local_id', sa.String(length=60), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('author_location', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('ratings_breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(place_id IS NOT NULL AND local_id IS NULL) OR (place_id IS NULL AND local_id IS NOT NULL)', name='check_review_target_exclusive'),
    sa.ForeignKeyConstraint(['local_id'], ['locals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_local_id'), 'reviews', ['local_id'], unique=False)
    op.create_index(op.f('ix_reviews_place_id'), 'reviews', ['place_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('saved_locals',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('local_id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'local_id', name='uq_user_saved_local')
    )
    op.create_index(op.f('ix_saved_locals_local_id'), 'saved_locals', ['local_id'], unique=False)
    op.create_index(op.f('ix_saved_locals_user_id'), 'saved_locals', ['user_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('itinerary_day_id', sa.String(length=60), nullable=False),
    sa.Column('place_id', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('time_slot', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.String(length=100), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_day_id'], ['itinerary_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_itinerary_day_id'), 'activities', ['itinerary_day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_itinerary_day_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_saved_locals_user_id'), table_name='saved_locals')
    op.drop_index(op.f('ix_saved_locals_local_id'), table_name='saved_locals')
    op.drop_table('saved_locals')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_place_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_local_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_itinerary_days_trip_id'), table_name='itinerary_days')
    op.drop_table('itinerary_days')
    op.drop_index(op.f('ix_concierge_requests_user_id'), table_name='concierge_requests')
    op.drop_index(op.f('ix_concierge_requests_status'), table_name='concierge_requests')
    op.drop_index(op.f('ix_concierge_requests_destination'), table_name='concierge_requests')
    op.drop_table('concierge_requests')
    op.drop_index(op.f('ix_bookings_traveler_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_local_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_status'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_destination'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_saved_places_user_id'), table_name='saved_places')
    op.drop_index(op.f('ix_saved_places_place_id'), table_name='saved_places')
    op.drop_table('saved_places')
    op.drop_index(op.f('ix_locals_verification_status'), table_name='locals')
    op.drop_index(op.f('ix_locals_city'), table_name='locals')
    op.drop_table('locals')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_places_verification_status'), table_name='places')
    op.drop_index(op.f('ix_places_name'), table_name='places')
    op.drop_index(op.f('ix_places_city'), table_name='places')
    op.drop_index(op.f('ix_places_category'), table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
